### DISCUSSION TITLE
HBridgeIC - H-bridge integrated circuit.

### DISCUSSION THREAD

**Discussion by IhorNehrutsa** [micropython/micropython#10983] [Ideas]
TB6612, L298, L293, L9110, DRV8871, DRV8837, DRV8838, BTS7960 etc.

Let's design HBridgeXXX classes here.

HBridge(discrete components) - motor control #12083 
PWM: Reduce inconsistencies between ports. #10817
PWM: Reduce inconsistencies between ports 2. #12084

**Comment by 2dof** [comment]
> Let's design H_bridge here.

Do You mean a driver for H_Bridge?

**Comment by sosi-deadeye** [comment]
I used in the past this module: https://www.sparkfun.com/products/14451 (TB6612FNG)
There is also this breakout board with L298N: https://bc-robotics.com/shop/l298n-motor-driver-board/ (5V !!)

`TB6612FNG` has a different logic as `L298N`.
The `short-breake` requires both direction pins to be high.

Here something to start (not tested with hardware):
```python
import math
from machine import Pin, PWM

U16 = 65535

class HBridge:
    """
    For TB66FNG12
    Datasheet: https://www.sparkfun.com/datasheets/Robotics/TB6612FNG.pdf
    Page: 4

    The modes of the bridge are:
    - Short brake
    - Turn Clockwise
    - Turn Counter clockwise
    - Stop (no breake, high impendance)
    - Standby (high impendance)
    """
    def __init__(self, pwm: PWM, ain1: Pin, ain2: Pin, standby: Pin, invert=False):
        self._pwm = pwm
        self._ain1 = ain1
        self._ain2 = ain2
        self._standby = standby
        if invert:
            # swapping methods
            self.left, self.right = self.right, self.left
            
        self._setup()

    def _setup(self):
        self._pwm.init(freq=1_000, duty_u16=0)
        self._ain1.init(mode=Pin.OUT, value=0)
        self._ain2.init(mode=Pin.OUT, value=0)
        self._standby.init(mode=Pin.OUT, value=0)
    
    @staticmethod
    def to_u16(value) -> int:
        return min(max(math.floor(value / 100 * U16), 0), U16)
        
    def stop_breake(self):
        """
        Short breake
        """
        self._pwm.duty_u16(0)
        self._ain1.value(1)
        self._ain2.value(1)
        self._standby.value(1)
    
    def stop(self):
        """
        Stop (high impendance)
        """
        self._pwm.duty_u16(U16)
        self._ain1.value(0)
        self._ain2.value(0)
        self._standby.value(1)
    
    def standby(self):
        """
        Standby, same like stop
        """
        self._pwm.duty_u16(0)
        self._ain1.value(0)
        self._ain2.value(0)
        self._standby.value(0)

    def left(self, speed: float | int = 100):
        """
        Turn motor left with a speed (0 - 100%) 
        """
        self._ain1.value(1)
        self._ain2.value(0)
        self._standby.value(1)
        self._pwm.duty_u16(self.to_u16(speed))

    def right(self, speed: float | int = 100):
        """
        Turn motor right with a speed (0 - 100%) 
        """
        self._ain1.value(0)
        self._ain2.value(1)
        self._standby.value(1)
        self._pwm.duty_u16(self.to_u16(speed))


motor1 = HBridge(PWM(Pin(10)), Pin(20), Pin(21), Pin(22))
motor2 = HBridge(PWM(Pin(12)), Pin(25), Pin(26), Pin(27), invert=True)
```

**Reply by rkompass** [reply]
I tried to work on this and landed here:
```
#  Micropython Drivers for H-Bridge Motor Drivers TB66FNG12 and L298
#
#  Datasheets: https://www.sparkfun.com/datasheets/Robotics/TB6612FNG.pdf  and
#              https://www.bc-robotics.com/datasheets/l298n.pdf
#
#  The drivers work in sign-magnitude mode.
#  The TB66FNG12 and L298 behave identically when the PWM signal is high.
#  They by design behave differently when the PWM signal is low:
#       The TB66FNG12 then is in Brake mode: Both motor outputs connected to GND.
#       The L298 then is in Stop mode: High impedance, both motor outputs not connected.
#
#  The modes of the bridges are:
#     - Brake (fast motor stop, both motor outputs connected)
#     - Stop (slow motor stop, no brake, high impendance)
#     - Turn Clockwise
#     - Turn Counter Clockwise

from machine import Pin, PWM

#  ----   Circuitry and Setup for TB6612  -----
#
# The TB6612 has 3 inputs for each motor: pwmA, Ain1, Ain2 for Motor A and pwmB, Bin1, Bin2 for Motor B.
# Connect these 3 inputs to 3 pins of the Microcontroller.
# Create a PWM object for the pwm pin like:        pwmA = machine.PWM(machine.Pin(2))
# Create Pin objects for the two input pins like:  Ain1, Ain2 = machine.Pin(3), machine.Pin(4)
# The TB6612 has a standby input for both motors that you don't need: connect it to Vcc (input side).
#     Setting this pin low would set both motors to high impedance (Stop) mode, which you achieve with this drivers Stop mode.

class HBridge6612:

    # The class initializer receives the direction pins as a 2-tuple or 2-list:
    #     motor = HBridge6612(pwmA, (Ain1, Ain2), freq = 2000)               or
    #     motor = HBridge6612(pwmA, reversed((Ain1, Ain2)), freq = 2000)     for exchange of Clockwise and CounterClw
    #
    def __init__(self, pwm, in12, freq=1000):
        self.pwm = pwm
        in12 = tuple(in12)   # make a tuple again in case we got a generator from reversed()
        self.in1 = in12[0]
        self.in2 = in12[1]
        self.pwm.init(freq=freq, duty_u16=0)
        for pin in (in12):
            pin.init(mode=Pin.OUT, value=0)
        # ----  Constants for Modes of the HBridge6612.go() function:  ----
        self.Brake      = 0b011    #  Brake: out1 = out2 = PGND  (both outputs connected to GND)
        self.Stop       = 0b000    #  Both outputs not connected (high impedance) <-- this is the same as if STBY-pin == 0
        self.Clockwise  = 0b110    #  Drive: out1 = VM, out2 = PGND if pwm == 1, otherwise brake: out1 = out2 = PGND
        self.CounterClw = 0b101    #  Drive: out1 = PGND, out2 = VM if pwm == 1, otherwise brake: out1 = out2 = PGND

    # motor.go(motor.Brake)
    # motor.go(motor.Stop)
    # motor.go(motor.Clockwise, 80)     # 80% speed forward
    # motor.go(motor.CounterCLw, 100)   # full speed backward
    #
    def go(self, mode, speed = 100):
        self.in1(mode>>1 & 1)
        self.in2(mode & 1)
        if mode > 3:
            self.pwm.duty_u16(min(int(speed*655.35), 65535))


#  ----   Circuitry and Setup for L298  -----
#
# The L298 has 3 inputs for each motor: in1, in2, enA for Motor A and in3, in4, enB for Motor B.
# Connect these 3 inputs to 3 pins of the Microcontroller.
# Create a PWM object for the enable pin like:     enA = machine.PWM(machine.Pin(2))
# Create Pin objects for the two input pins like:  in1, in2 = machine.Pin(3), machine.Pin(4)

class HBridge298:

    # The class initializer receives the direction pins as a 2-tuple or 2-list:
    # motor = HBridge298(enA, (in1, in2), freq = 2000)               or
    # motor = HBridge298(enA, reversed((in1, in2)), freq = 2000)     for exchange of Clockwise and CounterClw
    #
    def __init__(self, pwm, in12, freq=1000):
        self.pwm = pwm
        in12 = tuple(in12)
        self.in1 = in12[0]
        self.in2 = in12[1]
        self.pwm.init(freq=freq, duty_u16=0)
        for pin in (in12):
            pin.init(mode=Pin.OUT, value=0)
        # ----  Constants for Modes of the HBridge298.go() function:  ----
        self.Brake      = 0b011    #  Brake: out1 = out2 = PGND  (both outputs connected to GND)
        self.Stop       = 0b000    #  Both outputs not connected (high impedance) <-- this is the same as if STBY-pin == 0
        self.Clockwise  = 0b110    #  Drive: out1 = VM, out2 = PGND if pwm == 1, otherwise brake: out1 = out2 = PGND
        self.CounterClw = 0b101    #  Drive: out1 = PGND, out2 = VM if pwm == 1, otherwise brake: out1 = out2 = PGND

    # motor.go(motor.Brake)
    # motor.go(motor.Stop)
    # motor.go(motor.Clockwise, 80)     # 80% speed forward
    # motor.go(motor.CounterCLw, 100)   # full speed backward
    #
    def go(self, mode, speed = 100):
        self.in1(mode>>1 & 1)
        self.in2(mode & 1)
        if mode == 0:   # Stop mode ---> high impedance is achieved here with setting enable pin to 0
            self.pwm.duty_u16(0)       # ???? does this always work ???? Or should we change the pin mode to output and set it 0 ????
        elif mode == 3: # Brake mode ---> Both motor outputs to GND is achieved here with setting enable pin to 1
            self.pwm.duty_u16(65535)   # ???? does this always work ???? Or should we change the pin mode to output and set it 1 ????
        if mode > 3:
            self.pwm.duty_u16(min(int(speed*655.35), 65535))
```
You note that I applied my code-reduction-and-compactification routine:

- remove C-style constants where possible
- try to rewrite many functions into fewer ones by using additional/default arguments

But perhaps there are arguments against that?
With the code for the L298 I'm not sure I did it right.
There are questions: To define break or stop mode the pmw pin, which is the enable pin on the L298 in this version, has to be set to 0 or 1. Can we be sure that `pwm.duty_u16(0)` or `pwm.duty_u16(65535)` behave accordingly?

As of writing this I now see that having two PWM objects for the L298 would perhaps be better. Then for moderate Forward mode (i.e. Clockwise) we could set in2 to low and put in1 in pwm mode and this would correspond to a mix of driving and braking like with the 6612 driver. Currently we have a mix of driving and stopping (free float with high impedance).

I come to the conclusion that it is desirable to have a pwm.set(l) function which with with l=0 or l=1 would allow to set the pin like in output mode.

**Reply by rkompass** [reply]
Current incarnation of the code is:
```
#  Micropython Drivers for H-Bridge Motor Drivers TB66FNG12 and L298 and DRV8871
#
#  Datasheets: https://www.sparkfun.com/datasheets/Robotics/TB6612FNG.pdf  and
#              https://www.bc-robotics.com/datasheets/l298n.pdf
#              https://www.ti.com/lit/ds/symlink/drv8871.pdf
#
#  These drivers work in sign-magnitude mode.
#  When using PWM for Forward and Reverse mode they switch between driving and braking.
#  This is intended and also called slow synchronous current decay.
#  For an explanation see: TI Application Report "Current Recirculation and Decay Modes"
#                                     https://www.ti.com/lit/an/slva321a/slva321a.pdf
#  The modes of the bridges are:
#     - Forward (turn clockwise)
#     - Backward (turn counter-clockwise)
#     - Brake (fast motor stop, both motor outputs connected)
#     - Stop (Coast, slow motor stop, no brake, high impendance)
#
#  This code developed from a discussion on https://github.com/micropython/micropython/discussions/10983
#  Contributors: IhorNehrutsa, sosi-deadeye, rkompass


from machine import Pin, PWM


#  ----   Circuitry and Setup for TB6612  -----
#
#  in2 | in1 | pwm | stby
# -----------------------
#   X  |  X  |  X  |  L    Stop   (free running motor stop, i.e. high impedance)
# -----------------------
#   L  |  L  |  L  |  H    ????   (missing in datasheet)
#   L  |  L  |  H  |  H    Stop   (high impedance)
# -----------------------
#   L  |  H  |  L  |  H    Brake  (fast motor stop)
#   L  |  H  |  H  |  H    Forward
#   H  |  L  |  L  |  H    Brake  (fast motor stop)
#   H  |  L  |  H  |  H    Reverse
# -----------------------
#   H  |  H  |  X  |  H    Brake  (fast motor stop)
#
# The TB6612 has 3 inputs for each motor: Ain1, Ain2, pwmA for Motor A and Bin1, Bin2, pwmB for Motor B.
# Connect these 3 inputs to 3 pins of the Microcontroller.
# Create Pin objects for the two input pins like:  ain1, ain2 = machine.Pin(2), machine.Pin(3)
#    and a pin object for the pwm pin like:        pwma = machine.Pin(4)
# The TB6612 has a standby input for both motors that you don't need: connect it to Vcc (input side).
# Setting this pin low would set both motors to high impedance (Stop) mode, which you may achieve with this drivers Stop mode.

class HBridge6612:

    # The class initializer receives the direction pins as a 2-tuple or 2-list:
    #     motor = HBridge6612((ain1, ain2), pwma)                         # or
    #     motor = HBridge6612(reversed((ain1, ain2)), pwma, freq = 1000)  # for exchange of Clockwise and CounterClw
    #                                                                     #    and explicit setting of PWM frequency
    def __init__(self, in12, pwm, freq=1000):
        in12 = tuple(in12)   # make a tuple again in case we got a generator from reversed()
        self.in1 = in12[0]
        self.in2 = in12[1]
        self.pwm = PWM(pwm, freq=freq, duty_u16=0) # should start the pwm !!!?
        for pin in (in12):
            pin.init(mode=Pin.OUT, value=0)
        #  --  Constants for Modes of the HBridge6612.go() function:  --
        self.Stop = None     #  Both outputs not connected (high impedance)
        self.Brake = 0       #  Brake: out1 = out2 = PGND  (both outputs conn. to GND)

    # motor.go(80)          # Forward, 80% speed
    # motor.go(0)           # Brake,  (both motor outputs connected to GND)
    # motor.go(motor.Brake) #        --     ||     --
    # motor.go(-100)        # Backward, full speed
    # motor.go(None)        # Stop, (both motor outputs high impedance)
    # motor.go(motor.Stop)  #        --     ||     --
    #
    def go(self, speed):
        if speed > 0:
            self.in1(1); self.in2(0)
        elif speed < 0:
            self.in1(0); self.in2(1)
            speed = -speed
        elif speed == 0:               # speed == 0     --> Brake
            self.in1(1); self.in2(1)
        else:                          # speed == None  --> Stop
            self.in1(0); self.in2(0)
            speed = 0
        self.pwm.duty_u16(min(int(speed*655.35), 65535))


#  ----   Circuitry and Setup for L298  -----
#
#  in2 | in1 | enA
# -----------------
#   X  |  X  |  L    Stop   (free running motor stop, i.e. high impedance)
# -----------------
#   L  |  L  |  H    Brake  (fast motor stop)
#   L  |  H  |  H    Forward
#   H  |  L  |  H    Reverse
#   H  |  H  |  H    Brake  (fast motor stop)
# 
# The L298 has 3 inputs for each motor: in1, in2, enA for Motor A and in3, in4, enB for Motor B, of which
#   the two inputs in1, in2 (or in3, in4) are sufficient to control the motor.
# Connect these inputs to two pins of the Microcontroller.
# The enable pin enA (or enB) may be set with a jumper to H (high) or connected to a third pin of the microcontroller
#   if you want to be able to set the Stop mode (free running motor stop, i.e. high impedance) from the driver.
# Create Pin objects for the two input pins like:  in1, in2 = machine.Pin(2), machine.Pin(3)
# Optionally create an enable Pin object like: enA = machine.Pin(4) if you want to use Stop mode.

# Should also work with L293 (see Figure10, Table 3 of Datasheet)
# Should also work with L9110 (no enable pin)

class HBridge298:

    # The class initializer receives the direction pins as a 2-tuple or 2-list:
    # motor = HBridge298((in1, in2))                                 #  or
    # motor = HBridge298(reversed((in1, in2)), en=enA, freq = 2000)  #  for exchange of Clockwise and CounterClw
    #                                                                #  and Stop mode and user defined PWM frequency
    def __init__(self, in12, en=None, freq=1000):
        in12 = tuple(in12)   # make a tuple again in case we got a generator from reversed()
        self.pwm1 = PWM(in12[0], freq=freq, duty_u16=0)
        self.pwm2 = PWM(in12[1], freq=freq, duty_u16=0)
        self.en = en
        if en is not None:  
            self.en.init(mode=Pin.OUT, value=1)
        # --  Constants for Modes of the HBridge298.go() function:  --
        self.Stop = None   #  Both outputs not connected (high impedance)
        self.Brake = 0     #  Brake: out1 = out2 = PGND  (both outputs conn. to GND)

    # motor.go(80)          # Forward, 80% speed
    # motor.go(0)           # Brake,  (both motor outputs connected to GND)
    #   or motor.go(motor.Brake)
    # motor.go(-100)        # Backward, full speed
    # motor.go(None)        # Stop, (both motor outputs high impedance)
    #   or motor.go(motor.Stop)
    #
    def go(self, speed):
        self.pwm1.duty_u16(min(int(speed*655.35), 65535) if speed > 0 else 0)  # we somewhat rely on the pin being low at
        self.pwm2.duty_u16(min(int(-speed*655.35), 65535) if speed < 0 else 0) # duty_u16(0)
        if self.en is not None:
            self.en(1 if speed is not None else 0)


#  ----   Circuitry and Setup for DRV8871  -----
#
#   in2 | in1 
#  -----------
#    X  |  X     
#  -----------
#    L  |  L     Stop / Coast (free running motor stop, i.e. high impedance)
#    L  |  H     Forward
#    H  |  L     Reverse
#    H  |  H     Brake  (fast motor stop)
#
#  This is called IN-IN interface in the Datasheet
# 
# The DRV8871 has 2 inputs for the motor: in1, in2
# Connect these inputs to two pins of the Microcontroller.
# Create Pin objects for the two input pins like:  in1, in2 = machine.Pin(2), machine.Pin(3)



# ???? this driver relies on PWM signal high at pwm.duty_u16(65535)
# should we use an inverse option of pwm ????
# 
class HBridge8871:

    # The class initializer receives the direction pins as a 2-tuple or 2-list:
    # motor = HBridge8871((in1, in2))                            #  or
    # motor = HBridge8871(reversed((in1, in2)), freq = 2000)     #  for exchange of Clockwise and CounterClw
    #                                                            #  and user defined PWM frequency
    def __init__(self, in12, freq=1000):
        in12 = tuple(in12)   # make a tuple again in case we got a generator from reversed()
        self.pwm1 = PWM(in12[0], freq=freq, duty_u16=65535)
        self.pwm2 = PWM(in12[1], freq=freq, duty_u16=65535)
        # --  Constants for Modes of the HBridge298.go() function:  --
        self.Stop = None   #  Both outputs not connected (high impedance)
        self.Brake = 0     #  Brake: out1 = out2 = PGND  (both outputs conn. to GND)

    # motor.go(80)          # Forward, 80% speed
    # motor.go(0)           # Brake,  (both motor outputs connected to GND)
    #   or motor.go(motor.Brake)
    # motor.go(-100)        # Backward, full speed
    # motor.go(None)        # Stop, (both motor outputs high impedance)
    #   or motor.go(motor.Stop)
    #
    def go(self, speed):
        if speed is not None:
            self.pwm2.duty_u16(65535 - min(int(speed*655.35), 65535) if speed > 0 else 65535)  # we somewhat rely on the pin being
            self.pwm1.duty_u16(65535 - min(int(-speed*655.35), 65535) if speed < 0 else 65535) # high at duty_u16(65535)
        else:
            self.pwm1.duty_u16(0)
            self.pwm2.duty_u16(0)
```
The 8871 pwm.go() function will be changed to use inverted PWM mode, which assures that the pin signals are 1 at duty_u16(0) (see the above mentioned PWM: Reduce inconsistencies between ports. https://github.com/micropython/micropython/issues/10817)

I'm somewhat missing a feedback.
Are you o.k. with the just one pwm.go() function?
Now I also reduced the number of arguments to one as you see in the comments of this function.
I plan to check more chips/interface versions and name them, so that the submodules will be named accordingly and we can
collect a list of chips that behave according to the respective version.
