### DISCUSSION TITLE
How to get stubs to work for gc?

### DISCUSSION THREAD

**Discussion by Always-Self-Hosted** [micropython/micropython#13629] [Using MicroPython]
I am using vscodium and using micropython for a project. I installed stubs for my port with `pip install micropython-esp8266-stubs` into a venv, which i set my project to use that venvs interpreter, which seemed to work great at first. But then i wanted to use the `gc.threshold()` function and noticed i wasn't getting auto complete for it, or hints about the function signature or arg types. 

Right clicking on the gc import statement and "go to definition" shows me that the jedi language server is loading the stdlib stubs instead of the micropython ones. I've put in an issue to that project and they said that was a performance decision and sorry, fair enough. 

but i was looking for a workaround and i was hoping i could just put the `gc.py` implementation from micropython into my project and import it with a relative path to force my IDE to know about the functions, but i couldn't find the `gc.py` file, only the `gc.c` file. Which im guessing is correct, i guess micropython isn't a library its an interpreter and those functions are baked in?

So really what im trying to get help with, is how do we get our IDE's to show us the correct stubs for micropython? is this an issue specific to vscodium? (because we can't use pylance) or have others hit this issue and quietly found their own work arounds?

Any information or help would be greatly appreciated.

**Comment by Josverl** [comment]
A: Depends on the IDE and typechecker used

background - stubs for stdlib modules are handled differently than other stubs , some typecheckers can be configured(pyright/pylance) , some just can't deal and bail out unless you delete some files (mypy). And some just work but mix Micro and C Python for edge cases (pycharm). 

I usually do not install the stubs into a .venv , but to a typings folder ( the default for pylance/pyright) 
that works well with other type checkers as well. If you install it elswhere - adjusts the paths below.

The key ingedient is the **`typeshedPath = "typings"`** which can be set in several other ways as well

> pyproject.toml
```toml
[tool.pyright]
include = ["."]
ignore = ["**/typings"]
exclude = [
    ".*",
    "__*",
    "**/typings",
]

typeCheckingMode = "basic"
stubPath = "typings"
typeshedPath = "typings"
pythonPlatform = "Linux"

reportMissingModuleSource = "none"
reportUnnecessaryTypeIgnoreComment = "error"

[tool.mypy]
platform = "linux"
mypy_path = "typings"
files = "*.py"
exclude = [
    "typings[\\/].*",  
]

follow_imports = "silent"
follow_imports_for_stubs = true
no_site_packages = true
check_untyped_defs = true
disable_error_code = ["no-redef","assignment"] 

# snippets may re-use the same variable names
allow_redefinition = true


```
