### ISSUE TITLE
CI/Spinx: sphinxcontrib.jquery  extension missing

### ISSUE THREAD

**Issue by robert-hh** [micropython/micropython#12498]
When pushing a PR with documentation, I get the following error during teh CI phase. It complains, that sphinxcontrib.jquery is missing. I have the same problem when trying to build the documentation locally on my Debian bookworm system, and I cannot find/install the missing extension.
```
cd ../tools && python3 gen-cpydiff.py
sphinx-build -E -b html -d build//doctrees  -W --keep-going -j auto . build//html
Running Sphinx v7.2.6

Extension error:
Could not import extension sphinxcontrib.jquery (exception: No module named 'sphinxcontrib.jquery')
make: Leaving directory '/home/runner/work/micropython/micropython/docs'
make: *** [Makefile:67: html] Error 2
```

**Comment by Josverl** [comment]
updating the action workflow solves this,
not the most elegant fix though

```
name: Build docs

on:
  pull_request:
    paths:
      - docs/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - name: Install Python packages
      run: pip install Sphinx sphinxcontrib.jquery
    - name: Build docs
      run: TZ=UTC make -C docs/ html
```
I usually keep a requirements-docs.txt/toml file to have a single source of the requirements
